### PR TITLE
Add INotifyPropertyChanged to Builder classes

### LINKED ISSUE #78: Add hook for setter generation to enable INPC support on builders
We would like to use immutable objects for our application pipeline but when creating forms we need a mutable wrapper. Currently we write out mutable classes so.

    public class Person : ReactiveObject {

        public string Name {
                get{ return _Name; }
                set{ this.RaiseAndSetIfChanged(ref _Name, value); }
        }
    }

Now we can bind to Person in a WPF form. Would it be possible to have a hook that generates application specific setters for the builders and be able to specify a base class for the builder? This would simplify our application greatly.

Then again if you could just have a flag that generates INPC support for the builders then that would be great.

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #78

### CODE REVIEW

**Comment by eggapauli** [comment]
Looks very good, thanks.
However, the equality check is more general if you used `System.Collections.Generic.EqualityComparer<T>.Default.Equals(this.fieldName, value)`.

I also started working on it because I finally got it to build on my home machine, but I didn't add any tests. You can take a look at the [equality check](https://github.com/eggapauli/ImmutableObjectGraph/blob/add-inpc-to-builder/src/ImmutableObjectGraph.Generation/CodeGen%2BBuilderGen.cs#L224) for example. I also inlined `OnPropertyChanged` and used a string literal for the property name (because it's generated code I thought it doesn't matter).
But I obviously didn't consider everything because I don't know the code base as good as you do.

**Comment by AArnott** [comment]
Great. I was uncertain my equality check would be adequate. There's multiple things to consider. I'll brainstorm here with you later... gotta run for now.

**Comment by AArnott** [comment]
I think when the property value has a reference type, it'll be crucial that the field is updated and the event raised any time the reference changes, regardless of value equality between the two references. The reason is consumers such as WPF data binding can hook the value itself for its own property changes if it is a reference type, and if the reference changes, WPF has to reset all its subscriptions. 
The `==` operator defaults to reference equality for reference types. But this operator can be overloaded so using `object.ReferenceEquals` would be safer.

When the property is over a value type, the setter should either always assign the value and raise the event, or have an equality comparer that really works. An overridden `Equals` method would do the trick, as the `EqualityComparer<T>.Default.Equals` would then call it. But do we trust it, or do we always raise it for value types instead?
Given that I'm pretty sure different folks would give different answers as to what the right behavior should be, I wish there was a way to turn it over to the consumer to decide. I'm thinking through various ways to do that.

**Comment by AArnott** [comment]
Looking more into this, I see the immutable types' `WithFactory` method already use the `!=` operator to decide whether a value is significantly different enough to allocate a new object. I wonder if there are bugs there...

**Comment by eggapauli** [comment]
I proposed using `EqualityComparer` because I thought it's the standard way of how MVVM libraries are doing it. However I did a (very quick) research and found that there is no consensus:
* [ReactiveUI](https://github.com/reactiveui/ReactiveUI/blob/e2c01b8230de576e4e7a689828eebfd5193fbf67/ReactiveUI/IReactiveObject.cs#L98) uses `EqualityComparer`
* [MvvmLight](https://mvvmlight.codeplex.com/SourceControl/latest#GalaSoft.MvvmLight/GalaSoft.MvvmLight%20(PCL)/ObservableObject.cs) uses `EqualityComparer`
* [Caliburn.Micro](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/PropertyChangedBase.cs) doesn't offer anything, so the user has to decide when to raise the event.
* [Prism](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Mvvm/BindableBase.cs#L32) uses `object.Equals`

Your argument about WPF having to reset its bindings is very interesting. I wonder how MVVM libraries are dealing with this or if this is a known problem at all.

**Comment by AArnott** [comment]
I'm willing to bet that these other libraries may not be adequately tested enough to notice the bugs that they incur when using reference types in their fields with types that implement INPC themselves. 
I'm going to go with the `!=` operator, and test during code gen whether the operator is defined and if not, skip the test (and assume the value is different) which will make structs 'just work' and if folks want to be more precise about it, they can overload the operators to define them, quite possibly in terms of the default EqualityComparer.

**Comment by AArnott** [comment]
OK, in its final form, property setters have at least 3 unique sets of conditions (plus no condition at all) based on the type of field the property setter is for. 
I feel comfortable with the `!=` operator.

@eggapauli if you're interested in pursuing the EqualityComparer question with the other MVVM frameworks you found, I'll describe a repro for a bug that I suspect they all have if you want to verify it and file bugs against them.

**Comment by eggapauli** [comment]
Ok, super, thanks for implementing this.
`!=` will be fine for us, we can always filter out _duplicates_ using Rx.

I'll see if I can reproduce it myself, thanks for the help.

**Pull request merged**
