### PR TITLE
VS 2017

### PR DESCRIPTION
**Pull request by azeno**
Ok so I've managed to get it building, all tests are green and packages look ok but I've tried them locally and sadly they don't seem to work. The GenerateCodeFromAttribute task gets executed (from what I see in the msbuild log) but the generated files are all empty except for the header comment.

Do you have any ideas on how to debug this? What's the difference between referencing through package and referencing directly? For the local projects in the solution (RoslynDemo and the test project) the files get generated properly.

### CODE REVIEW

**Comment by AArnott** [comment]
Thanks! I'll take a look this weekend.

**Comment by AArnott** [comment]
I've confirmed that the tests pass locally for me as well. I also fixed up the xunit build warnings. I'm testing the packaging now since you brought that up as an issue.

**Comment by AArnott** [comment]
I see what you mean about it not working in packaged form. I expect I can figure it out.

**Comment by AArnott** [comment]
I've pushed new commits to my own vs2017 branch. It's closer, but not there yet. :(

**Comment by AArnott** [comment]
OK. I've got it working. It required some fixes here, and some fixes to CG.R. Once I get the fixed CG.R pushed to nuget.org, I'll update this branch to consume it, verify it once more, then complete this PR.

**Comment by AArnott** [comment]
Got it. Thanks so much for your help getting this done, @azeno !

**Comment by azeno** [comment]
Perfect! Looking forward to update to it tomorrow.

**Pull request merged**
